### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by SteveRussell33** [21kHz/21kHz-rack-plugins#2]
Tried to compile clone Win 10 against Rack SDK 0.6.2
Output:

g++  -Wsuggest-override -std=c++11  -DSLUG=21kHz -fPIC -I../../include -I../../dep/include -DVERSION=0.6.1 -MMD -MP -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES -c -o build/src/PalmLoop.cpp.o src/PalmLoop.cpp
src/PalmLoop.cpp: In member function 'virtual void PalmLoop::step()':
src/PalmLoop.cpp:145:86: warning: 'float rack::clampf(float, float, float)' is deprecated [-Wdeprecated-declarations]
         outputs[SAW_OUTPUT].value = clampf(10.0f * (sawBuffer[0] - 0.5f), -5.0f, 5.0f);
                                                                                      ^
In file included from ../../include/util/common.hpp:85,
                 from ../../include/rack.hpp:4,
                 from src/21kHz.hpp:1,
                 from src/PalmLoop.cpp:1:
../../include/util/math.hpp:337:25: note: declared here
 DEPRECATED inline float clampf(float x, float min, float max) {return clamp(x, min, max);}
                         ^~~~~~
src/PalmLoop.cpp:145:86: warning: 'float rack::clampf(float, float, float)' is deprecated [-Wdeprecated-declarations]
         outputs[SAW_OUTPUT].value = clampf(10.0f * (sawBuffer[0] - 0.5f), -5.0f, 5.0f);
                                                                                      ^
In file included from ../../include/util/common.hpp:85,
                 from ../../include/rack.hpp:4,
                 from src/21kHz.hpp:1,
                 from src/PalmLoop.cpp:1:
../../include/util/math.hpp:337:25: note: declared here
 DEPRECATED inline float clampf(float x, float min, float max) {return clamp(x, min, max);}
                         ^~~~~~
src/PalmLoop.cpp:167:79: warning: 'float rack::clampf(float, float, float)' is deprecated [-Wdeprecated-declarations]
         outputs[SQR_OUTPUT].value = clampf(4.9999f * sqrBuffer[0], -5.0f, 5.0f);
                                                                               ^
In file included from ../../include/util/common.hpp:85,
                 from ../../include/rack.hpp:4,
                 from src/21kHz.hpp:1,
                 from src/PalmLoop.cpp:1:
../../include/util/math.hpp:337:25: note: declared here
 DEPRECATED inline float clampf(float x, float min, float max) {return clamp(x, min, max);}
                         ^~~~~~
src/PalmLoop.cpp:167:79: warning: 'float rack::clampf(float, float, float)' is deprecated [-Wdeprecated-declarations]
         outputs[SQR_OUTPUT].value = clampf(4.9999f * sqrBuffer[0], -5.0f, 5.0f);
                                                                               ^
In file included from ../../include/util/common.hpp:85,
                 from ../../include/rack.hpp:4,
                 from src/21kHz.hpp:1,
                 from src/PalmLoop.cpp:1:
../../include/util/math.hpp:337:25: note: declared here
 DEPRECATED inline float clampf(float x, float min, float max) {return clamp(x, min, max);}
                         ^~~~~~
src/PalmLoop.cpp:186:86: warning: 'float rack::clampf(float, float, float)' is deprecated [-Wdeprecated-declarations]
         outputs[TRI_OUTPUT].value = clampf(10.0f * (triBuffer[0] - 0.5f), -5.0f, 5.0f);
                                                                                      ^
In file included from ../../include/util/common.hpp:85,
                 from ../../include/rack.hpp:4,
                 from src/21kHz.hpp:1,
                 from src/PalmLoop.cpp:1:
../../include/util/math.hpp:337:25: note: declared here
 DEPRECATED inline float clampf(float x, float min, float max) {return clamp(x, min, max);}
                         ^~~~~~
src/PalmLoop.cpp:186:86: warning: 'float rack::clampf(float, float, float)' is deprecated [-Wdeprecated-declarations]
         outputs[TRI_OUTPUT].value = clampf(10.0f * (triBuffer[0] - 0.5f), -5.0f, 5.0f);
                                                                                      ^
In file included from ../../include/util/common.hpp:85,
                 from ../../include/rack.hpp:4,
                 from src/21kHz.hpp:1,
                 from src/PalmLoop.cpp:1:
../../include/util/math.hpp:337:25: note: declared here
 DEPRECATED inline float clampf(float x, float min, float max) {return clamp(x, min, max);}
                         ^~~~~~
g++ -o plugin.dll build/src/21kHz.cpp.o build/src/D_Inf.cpp.o build/src/PalmLoop.cpp.o  -shared -L../.. -lRack

**Comment by jakehuryn** [comment]
hey, sorry for the lack of response. tbh i can't really tell what the problem is here, all i can see are the "clampf deprecated" warnings (i'll get around to stopping using clampf eventually, hopefully). but i'm very close to finishing 0.6.1, so it should hopefully be in the plugin manager soon if you're still having trouble compiling.
