### ISSUE TITLE
[enhancement] Tachyone Entangler

### ISSUE THREAD

**Issue by Eurikon** [21kHz/21kHz-rack-plugins#3]
Hi there, thanks for these great modules!

I just tried out T.E. and like it a lot, it can create nice and soothing sounds, to crazy weird noise!

About the Chaos rotation knob, would it be an idea to have either an attenuator for it, ora slector knob next to it with 3 different settings: max,med,min.
Where max is how it is now, medium 50% of max spread out over the rotation knob resolution, 30% of max spread out over the rotation knob resolution.

Cause the 100% it has now is very wild, the more interesting subtle effects are in the very first start positions of the rotation knob, after that it quickly turns into noise.

**Comment by jakehuryn** [comment]
yeah, i was thinking about that too. i'll figure out some way to make it more precise on the smaller end for the next update. thanks for the feedback!
